name: Go CI/CD Pipeline

on:
  push:
    branches: [ master, develop, 'feature/**', 'release/**', 'hotfix/**' ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build application
      run: go build -v -o app .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-app
        path: app

  deploy-staging:
    name: Deploy to Staging
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: go-app
    
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment..."
        echo "App would be deployed here"

  deploy-production:
    name: Deploy to Production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: go-app
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production environment..."
        echo "App would be deployed here"
